# Generated by Django 2.1.7 on 2019-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(error_messages={'unique': 'This Subject ID has already been registered.'}, max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_note', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
