# Generated by Django 2.1.7 on 2019-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=255)),
                ('exam_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(default='0000-00-00 00:00:00')),
                ('end_date', models.DateTimeField(default='0000-00-00 00:00:00')),
            ],
            options={
                'db_table': 'exam',
            },
        ),
    ]
