# Generated by Django 2.1.7 on 2019-08-13 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
        ('exam', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks1', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('marks2', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('marks3', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('marks4', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('marks5', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('marks6', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('marks7', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('marks8', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('marks9', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('marks10', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('classes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.Classes')),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.Exam')),
                ('subject1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='content.Subject')),
                ('subject10', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject10', to='content.Subject')),
                ('subject2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='content.Subject')),
                ('subject3', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='content.Subject')),
                ('subject4', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject4', to='content.Subject')),
                ('subject5', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject5', to='content.Subject')),
                ('subject6', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject6', to='content.Subject')),
                ('subject7', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject7', to='content.Subject')),
                ('subject8', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject8', to='content.Subject')),
                ('subject9', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject9', to='content.Subject')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marks',
            },
        ),
    ]
