# Generated by Django 2.1.7 on 2019-06-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20190626_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_no',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=20),
        ),
    ]
