# Generated by Django 2.1.7 on 2019-06-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20190626_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='teacher',
        ),
    ]
